import type { Presentation, Slide } from '../schema/presentation.js';
import type { TemplateCapabilities } from '../schema/capabilities.js';

/**
 * Builds the demo AST per spec section 6.1 (14-16 slides).
 * Slides 15-16 are degradation demos, generated only when the
 * target layout is absent from the template.
 *
 * Separated from demoGenerator.ts to isolate fixture data from
 * pipeline orchestration.
 */
export function buildDemoAST(capabilities: TemplateCapabilities): Presentation {
  const supported = new Set(capabilities.supported_layouts);
  const slides: Slide[] = [];

  // #1 — LAYOUT_TITLE: nominal
  slides.push({
    layout: 'title',
    elements: [
      { type: 'title', text: 'Demo Presentation' },
      { type: 'subtitle', text: 'Generated by pptx-generator validator' },
    ],
    notes: 'Slide 1: Nominal title layout — title + subtitle rendering.',
  });

  // #2 — LAYOUT_SECTION: nominal
  slides.push({
    layout: 'section',
    elements: [
      { type: 'title', text: 'Section Break' },
      { type: 'subtitle', text: 'This is a section divider slide' },
    ],
    notes: 'Slide 2: Nominal section layout.',
  });

  // #3 — LAYOUT_BULLETS: 3 short bullets
  slides.push({
    layout: 'bullets',
    elements: [
      { type: 'title', text: 'Three Short Bullets' },
      { type: 'bullets', items: ['First point', 'Second point', 'Third point'] },
    ],
    notes: 'Slide 3: Standard case with 3 short bullets.',
  });

  // #4 — LAYOUT_BULLETS: 5 bullets (max)
  slides.push({
    layout: 'bullets',
    elements: [
      { type: 'title', text: 'Five Bullets (Max)' },
      {
        type: 'bullets',
        items: [
          'First item in the list',
          'Second item in the list',
          'Third item in the list',
          'Fourth item in the list',
          'Fifth item in the list',
        ],
      },
    ],
    notes: 'Slide 4: Maximum 5 bullets — verifying all fit.',
  });

  // #5 — LAYOUT_BULLETS: text too long (25 words per bullet)
  const longBullet = 'This is a very long bullet point that contains many words to test how the system handles overflow when the content exceeds the expected maximum length per line';
  slides.push({
    layout: 'bullets',
    elements: [
      { type: 'title', text: 'Long Text Overflow Test' },
      {
        type: 'bullets',
        items: [longBullet, longBullet, longBullet],
      },
    ],
    notes: 'Slide 5: Overflow test — each bullet has ~25 words.',
  });

  // #6 — LAYOUT_BULLETS: 2-line title
  slides.push({
    layout: 'bullets',
    elements: [
      {
        type: 'title',
        text: 'This Is a Very Long Title That Should Wrap Onto Two Lines to Test Title Overflow Handling',
      },
      { type: 'bullets', items: ['Content under long title'] },
    ],
    notes: 'Slide 6: Long title wrapping test (>60 chars).',
  });

  // #7 — LAYOUT_TWO_COLUMNS: nominal
  slides.push({
    layout: 'twoColumns',
    elements: [
      { type: 'title', text: 'Two Columns — Balanced' },
      { type: 'bullets', items: ['Left item A', 'Left item B', 'Left item C'], column: 'left' },
      { type: 'bullets', items: ['Right item A', 'Right item B', 'Right item C'], column: 'right' },
    ],
    notes: 'Slide 7: Nominal two-columns layout — balanced columns.',
  });

  // #8 — LAYOUT_TWO_COLUMNS: unbalanced (5 vs 2)
  slides.push({
    layout: 'twoColumns',
    elements: [
      { type: 'title', text: 'Two Columns — Unbalanced' },
      {
        type: 'bullets',
        items: ['Left 1', 'Left 2', 'Left 3', 'Left 4', 'Left 5'],
        column: 'left',
      },
      { type: 'bullets', items: ['Right 1', 'Right 2'], column: 'right' },
    ],
    notes: 'Slide 8: Unbalanced columns — 5 vs 2 bullets.',
  });

  // #9 — LAYOUT_TIMELINE: 4 events with mixed statuses
  slides.push({
    layout: 'timeline',
    elements: [
      { type: 'title', text: 'Project Timeline — 4 Events' },
      {
        type: 'timeline',
        events: [
          { date: '2026-Q1', label: 'Planning', status: 'done' },
          { date: '2026-Q2', label: 'Development', status: 'done' },
          { date: '2026-Q3', label: 'Testing', status: 'in-progress' },
          { date: '2026-Q4', label: 'Launch', status: 'planned' },
        ],
      },
    ],
    notes: 'Slide 9: Timeline with 4 events — mixed statuses (done/in-progress/planned).',
  });

  // #10 — LAYOUT_TIMELINE: 6 events (max)
  slides.push({
    layout: 'timeline',
    elements: [
      { type: 'title', text: 'Timeline — 6 Events (Max)' },
      {
        type: 'timeline',
        events: [
          { date: 'Jan', label: 'Kickoff', status: 'done' },
          { date: 'Mar', label: 'Prototype', status: 'done' },
          { date: 'May', label: 'Alpha', status: 'done' },
          { date: 'Jul', label: 'Beta', status: 'in-progress' },
          { date: 'Sep', label: 'RC', status: 'planned' },
          { date: 'Nov', label: 'GA Release', status: 'planned' },
        ],
      },
    ],
    notes: 'Slide 10: Timeline with 6 events — edge case for max events.',
  });

  // #11 — LAYOUT_ARCHITECTURE: 3 layers, 4 nodes
  slides.push({
    layout: 'architecture',
    elements: [
      { type: 'title', text: 'Architecture — Simple' },
      {
        type: 'diagram',
        nodes: [
          { id: 'ui', label: 'Web UI', layer: 'Frontend' },
          { id: 'api', label: 'API Gateway', layer: 'Backend' },
          { id: 'svc', label: 'Service', layer: 'Backend' },
          { id: 'db', label: 'Database', layer: 'Data' },
        ],
        edges: [
          { from: 'ui', to: 'api' },
          { from: 'api', to: 'svc' },
          { from: 'svc', to: 'db' },
        ],
      },
    ],
    notes: 'Slide 11: Simple architecture — 3 layers, 4 nodes.',
  });

  // #12 — LAYOUT_ARCHITECTURE: 3 layers, 8 nodes (max)
  slides.push({
    layout: 'architecture',
    elements: [
      { type: 'title', text: 'Architecture — Complex (8 Nodes)' },
      {
        type: 'diagram',
        nodes: [
          { id: 'web', label: 'Web App', layer: 'Presentation' },
          { id: 'mobile', label: 'Mobile App', layer: 'Presentation' },
          { id: 'gw', label: 'API Gateway', layer: 'Services' },
          { id: 'auth', label: 'Auth Service', layer: 'Services' },
          { id: 'core', label: 'Core Service', layer: 'Services' },
          { id: 'cache', label: 'Redis Cache', layer: 'Data' },
          { id: 'pg', label: 'PostgreSQL', layer: 'Data' },
          { id: 's3', label: 'Object Store', layer: 'Data' },
        ],
        edges: [
          { from: 'web', to: 'gw' },
          { from: 'mobile', to: 'gw' },
          { from: 'gw', to: 'auth' },
          { from: 'gw', to: 'core' },
          { from: 'core', to: 'cache' },
          { from: 'core', to: 'pg' },
          { from: 'core', to: 's3' },
        ],
      },
    ],
    notes: 'Slide 12: Complex architecture — 3 layers, 8 nodes (edge case).',
  });

  // #13 — LAYOUT_GENERIC: free text
  slides.push({
    layout: 'generic',
    elements: [
      { type: 'title', text: 'Generic Layout — Free Text' },
      { type: 'text', text: 'This slide uses the generic layout with free-form text content. It serves as the ultimate fallback for any unsupported layout type.' },
    ],
    notes: 'Slide 13: Generic layout — plain text body.',
  });

  // #14 — LAYOUT_GENERIC: bullets in fallback
  slides.push({
    layout: 'generic',
    elements: [
      { type: 'title', text: 'Generic Layout — Bullets Fallback' },
      { type: 'bullets', items: ['Bullet in generic body A', 'Bullet in generic body B', 'Bullet in generic body C'] },
    ],
    notes: 'Slide 14: Generic layout — bullets rendered in body placeholder.',
  });

  // #15 — Degradation: kpi → bullets (only if kpi not supported)
  if (!supported.has('kpi')) {
    slides.push({
      layout: 'kpi',
      elements: [
        { type: 'title', text: 'KPI Dashboard (Degraded)' },
        {
          type: 'kpi',
          indicators: [
            { label: 'Revenue', value: '1.2M', unit: 'USD', trend: 'up' },
            { label: 'Users', value: '50K', trend: 'stable' },
            { label: 'Churn', value: '2.1%', trend: 'down' },
          ],
        },
      ],
      notes: 'Slide 15: Degradation demo — kpi layout degraded to bullets.',
    });
  }

  // #16 — Degradation: architecture → generic (only if architecture not supported)
  if (!supported.has('architecture')) {
    slides.push({
      layout: 'architecture',
      elements: [
        { type: 'title', text: 'Architecture Diagram (Degraded)' },
        {
          type: 'diagram',
          nodes: [
            { id: 'a', label: 'Frontend', layer: 'UI' },
            { id: 'b', label: 'Backend', layer: 'API' },
          ],
          edges: [{ from: 'a', to: 'b' }],
        },
      ],
      notes: 'Slide 16: Degradation demo — architecture layout degraded to generic/bullets.',
    });
  }

  return {
    title: 'Template Demo — pptx-generator',
    metadata: {
      author: 'pptx-generator validator',
      date: new Date().toISOString().slice(0, 10),
      version: '1.0.0',
    },
    slides,
  };
}
